### ISSUE TITLE
Tracker for v1.0.0 release

### ISSUE THREAD

**Issue by phoenisx** [willofindie/vscode-gohugo#1]
- [x] Support Archetypes
  - Support default and archtype templates both in same command.
  - Done as part of [Release 0.1.0](https://github.com/willofindie/vscode-gohugo/releases/tag/v0.1.0)
- [ ] Support `hugo convert`
- [ ] Support `hugo deploy`
- [ ] Support `hugo config`
  - Not sure how important this command will be?? Anyways, will keep it for last.
- [ ] Support build environments
- [ ] Support `hugo list` command
